## docker-compose -p webots -f docker-compose-webots.yaml up
version: "2.3"
services:
  xserver:
    image: jskrobotics/agent_system:xserver_2021
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80" ## 3000 is port for http / open http://localhost:3000 with web browser
    environment:
      - DISPLAY=:1
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1s"
      retries: 20
  main:
    image: jskrobotics/agent_system:webots_2021
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    command: [bash, -c, 'until xset q; do sleep 3; done && webots']
    #command: [bash, -c, 'until xset q; do sleep 3; done && roslaunch robot_assembler kxr_assembler.launch']
    #command: [bash, -c, 'while true; do sleep 5; done'] ##for debug
    #command: [ /entrypoint_xserver.sh, roslaunch, target_pkg, target.launch ]
    environment:
      - DISPLAY=:1
      - DOCKER_ROS_SETUP=/catkin_ws/install/setup.bash
      - DOCKER_ROS_IP=localhost
      # - ROS_MASTER_URI=http://localhost:11311
      # - ROS_IP=localhost
      # - ROS_HOSTNAME=localhost
      # - ROS_HOME=/ros_home
              ## mount directory /tmp/jskrobotics -> docker:/jsk_robotics
    volumes:  ## you can change /tmp/jskrobotics to your favorite directory
      - '/tmp/jskrobotics:/jskrobotics'
    volumes_from:
      - xserver
    depends_on:
      - xserver
